spring.datasource.url=jdbc:sqlite:blog.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.file.name=spring.log
logging.level.org.springframework.web=DEBUG
server.error.include-exception=true
server.error.include-stacktrace=always
server.error.include-message=always
